# EZchat v2.8
# Configuration File
# Do not rename this file!

# After making any changes, reload the config from the admin panel or restart EZchat.



# Basic config
[basic]

# name at the top of the website
siteName = "EZchat v2.8"

# name in the tab
siteTitle = "EZchat"

# message below the name, leave empty to remove
motd = "Have a wonderful day!"

# escape button link, leave empty to remove
escapeLink = "https://google.com"

# how many recent messages to cache and send to new connections
# must be an integer greater than -1
# set to 0 to cache and send no messages
recentMsgs = 20

# username length limit
userCharLimit = 20

# message length limit
messageCharLimit = 200



# File system
[fs]

# toggles file system support
fileSystem = true

# accepted file extensions
filterFileExts = false
allowedFileExts = [".apng", ".avif", ".gif", ".jpg", ".jpeg", ".jfif", ".pjpeg", ".pjp", ".png", ".svg", ".webp", ".ogg", ".mp4", ".webm"]

# file extensions in the blocked list will be blocked
# no matter the value of filterFileExts
blockedFileExts = [".exe", ".php", "", ".bin"]

# auto display images and videos
autoDisplayImages = true

# file storage directory
# REMOVE EXECUTE PERMISSIONS FROM THIS FOLDER
fsDirectory = "filesystem"

# file size limit (MB)
# set to 0 to remove limit
fileSizeLimit = 8

# max number of stored files
# note: changing value to less that it was will not delete files
# set to 0 to store infinite files
maxFiles = 0

# set stored file names to a secure name rather than the display name
secureFileNames = true



# Admin stuff
[admin]

# admin uids
adminUids = ["admin_uid1", "admin_uid2", "PkRlns8WAZpwRjzQpDXjcA"]

# use ?admin=true attribute
# HUGE SECURITY PROBLEM
useAdminAttribute = false



# Advanced settings, do not change unless you know what you are doing!!
[advanced]

# ports to use
# if changing ports, change in appsettings.json to reflect it for first-time users.
ports = [80, 443]

# ip address
addr = "0.0.0.0"

# file locations
# locations based in the Application base directory
msglog = "admin/msglog.txt"
banlist = "admin/banlist.txt"

# After making any changes, restart EZchat.