# EZchat v2.8
# Configuration File
# Do not rename this file!

# After making any changes, reload the config from the admin panel or restart EZchat.



# Basic config
[basic]

# name at the top of the website
siteName = "EZchat v2.8"

# name in the tab
siteTitle = "EZchat"

# message below the name, leave empty to remove
motd = "Have a wonderful day!"

# escape button link, leave empty to remove
escapeLink = "https://google.com"

# how many recent messages to cache and send to new connections
# must be an integer greater than -1
# set to 0 to cache and send no messages
recentMsgs = 20



# File system
[fs]

# toggles file system support
fileSystem = true

# filter file extensions
filterFileExts = true
allowedFileExts = [".png", ".jpg", ".jpeg"]
blockedFileExts = [".exe", ".bin"]

# auto display images
autoDisplayImages = true
imageFileExts = [".png", ".jpg", ".jpeg"]

# file storage directory
# REMOVE EXECUTE PERMISSIONS FROM THIS FOLDER
fsDirectory = "filesystem"

# file size limit (MB)
# set to 0 to remove limit
fileSizeLimit = 50

# max number of stored files
# note: changing value to less that it was will not delete files
# set to 0 to store infinite files
maxFiles = 0



# Admin stuff
[admin]

# admin uids
adminUids = ["admin_uid1", "admin_uid2", "PkRlns8WAZpwRjzQpDXjcA"]

# use ?admin=true attribute
# HUGE SECURITY PROBLEM
useAdminAttribute = false



# Advanced settings, do not change unless you know what you are doing!!
[advanced]

# ports to use
# if changing ports, change in appsettings.json to reflect it for first-time users.
ports = [80, 443]

# ip address
addr = "0.0.0.0"

# file locations
# locations based in the Application base directory
msglog = "admin/msglog.txt"
banlist = "admin/banlist.txt"

# After making any changes, restart EZchat.